welcome:
  text:
    ru: Добро пожаловать, я выдаю конфигурационные файлы для подключения к WireGuard VPN. Используй команду /conf для получения файла.
    eng: Welcome, I can send u configuration file for WireGuard VPN. Use /conf command to get your conf file.
  # possible options
  # parse_mode: "HTML" | "MarkdownV2"
  # disable_notification: yes | no
  # protect_content: yes | no
  # disable_web_page_preview: yes | no
  message_effect_id: '5159385139981059251'
successfully_created:
  text:
    ru: |
      Ваш конфигурационный файл успешно создан\.

      Чтобы подключить к серверу, используйте официального приложение WireGuard\.
      [Android](https://play.google.com/store/apps/details?id=com.wireguard.android) \| [iOS](https://itunes.apple.com/us/app/wireguard/id1441195209?ls=1&mt=8)
      
      ||Данное сообщение защищено от пересылки||
    eng: | 
      Your conf file was successfully created\.

      To connect to server use official WireGuard app\.
      [Android](https://play.google.com/store/apps/details?id=com.wireguard.android) \| [iOS](https://itunes.apple.com/us/app/wireguard/id1441195209?ls=1&mt=8)

      ||This message is protected from forwarding||
  protect_content: yes
  parse_mode: 'MarkdownV2'
your_png:
  text:
    ru: |
      QR-код для подключения к серверу\.

      Отсканируйте данный QR-код с помощью официального приложения Wireguard\.
      [Android](https://play.google.com/store/apps/details?id=com.wireguard.android) \| [iOS](https://itunes.apple.com/us/app/wireguard/id1441195209?ls=1&mt=8)

      ||Данное сообщение защищено от пересылки||
    en: |
      QR-code to connect to server\.

      Scan it using official WireGuard app.
      [Android](https://play.google.com/store/apps/details?id=com.wireguard.android) \| [iOS](https://itunes.apple.com/us/app/wireguard/id1441195209?ls=1&mt=8)

      ||This message is protected from forwarding||
  protect_content: yes
  parse_mode: 'MarkdownV2'
not_created:
  text:
    ru: Произошла ошибка при генерации конфигурации.
    en: An issue occured while creating config.
