welcome:
  text:
    ru: Добро пожаловать, я выдаю конфигурационные файлы для подключения к WireGuard VPN. Используй команду /conf для получения файла.
    eng: Welcome, I can send u configuration file for WireGuard VPN. Use /conf command to get your conf file.
  # possible options
  # parse_mode: "HTML" | "MarkdownV2"
  # disable_notification: yes | no
  # protect_content: yes | no
  # disable_web_page_preview: yes | no
  message_effect_id: '5159385139981059251'
successfully_created:
  text:
    ru: |
      Ваш конфигурационный файл успешно создан\.

      ||Данное сообщение защищено от пересылки||
    eng: | 
      Your conf file was successfully created\.

      ||This message is protected from forwarding||
  protect_content: yes
  parse_mode: 'MarkdownV2'
not_created:
  text:
    ru: Произошла ошибка при генерации qr-кода.
    en: An issue occured while creating qr-code.
